# Generated by Django 4.2.6 on 2023-11-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
