# Generated by Django 4.2.6 on 2024-03-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('EMPLOYEE', 'Employee'), ('PLACEMENTOFFICER', 'placementofficer')], max_length=64),
        ),
    ]
