# Generated by Django 4.2.6 on 2024-05-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('EMPLOYEE', 'Employee'), ('PLACEMENTOFFICER', 'placementofficer'), ('ACCOUNT', 'account')], max_length=64),
        ),
    ]
