# Generated by Django 4.1.4 on 2023-09-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
