# Generated by Django 4.2.6 on 2024-03-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees_erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.TextField()),
                ('document1', models.FileField(upload_to='student/fees')),
                ('document2', models.FileField(upload_to='student/fees')),
                ('document3', models.FileField(upload_to='student/fees')),
                ('student', models.ForeignKey(db_column='student', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
