# Generated by Django 4.2.6 on 2024-03-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_erp', '0003_alter_splitpayment_options_alter_splitpayment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitpayment',
            name='allow_split_payment',
            field=models.BooleanField(default=False),
        ),
    ]
