# Generated by Django 4.2.6 on 2024-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_erp', '0004_splitpayment_allow_split_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitpayment',
            name='document1',
            field=models.FileField(blank=True, upload_to='student/fees'),
        ),
        migrations.AlterField(
            model_name='splitpayment',
            name='document2',
            field=models.FileField(blank=True, upload_to='student/fees'),
        ),
        migrations.AlterField(
            model_name='splitpayment',
            name='document3',
            field=models.FileField(blank=True, upload_to='student/fees'),
        ),
    ]
