# Generated by Django 4.2.6 on 2024-03-06 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_studentgroups_counsellorgroups'),
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
        ('fees_erp', '0005_alter_splitpayment_document1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=25)),
                ('order_id', models.CharField(max_length=25)),
                ('transaction_id', models.CharField(max_length=25)),
                ('transaction_amount', models.CharField(max_length=12)),
                ('transaction_status', models.CharField(max_length=25)),
                ('payment_method', models.CharField(max_length=25)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(db_column='batch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='batches.batches')),
                ('branch', models.ForeignKey(db_column='branch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branches')),
                ('group', models.ForeignKey(db_column='group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groups')),
                ('student', models.ForeignKey(db_column='student', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Fees',
                'db_table': 'student_fees',
            },
        ),
    ]
