# Generated by Django 4.2.6 on 2023-11-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_name', models.CharField(db_column='group_name', max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
            },
        ),
    ]
