# Generated by Django 4.2.6 on 2023-12-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_field', models.CharField(max_length=15)),
                ('dropdown_value', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Dropdown values for Infrastructure Form',
                'db_table': 'infrastructure_categories',
            },
        ),
        migrations.CreateModel(
            name='InfrastructureForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=75, unique=True)),
                ('institute', models.CharField(max_length=5)),
                ('department', models.CharField(max_length=10)),
                ('room_category', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=3)),
                ('item_type', models.CharField(max_length=25)),
                ('year_of_purchase', models.CharField(max_length=4)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Infrastructure List',
                'db_table': 'infrastructure',
            },
        ),
    ]
