# Generated by Django 4.2.6 on 2023-12-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructurecategories',
            name='form_field',
            field=models.CharField(choices=[('institute', 'institute'), ('department', 'department'), ('room_category', 'room_category'), ('item_type', 'item_type')], max_length=15),
        ),
    ]
