# Generated by Django 4.2.6 on 2023-11-26 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsellor', models.OneToOneField(db_column='counsellor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_name', models.ForeignKey(db_column='group_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groups')),
            ],
            options={
                'verbose_name_plural': 'Counsellors-Groups',
                'db_table': 'counsellor_groups',
            },
        ),
    ]
