# Generated by Django 4.2.6 on 2023-12-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tution_fee', models.CharField(default='0', max_length=8)),
                ('activity_fee', models.CharField(default='0', max_length=8)),
                ('university_fee', models.CharField(default='0', max_length=8)),
                ('security_fee', models.CharField(default='0', max_length=8)),
                ('college_magazine', models.CharField(default='0', max_length=8)),
                ('rechecking_fee', models.CharField(default='0', max_length=8)),
                ('reappear_fee', models.CharField(default='0', max_length=8)),
                ('fine', models.CharField(default='0', max_length=8)),
                ('institute_alumni_contribution', models.CharField(default='0', max_length=8)),
                ('book_bank', models.CharField(default='0', max_length=8)),
                ('total_fee', models.CharField(blank=True, max_length=8, null=True)),
                ('display_tution_fee', models.BooleanField(default=True)),
                ('display_activity_fee', models.BooleanField(default=True)),
                ('display_university_fee', models.BooleanField(default=True)),
                ('display_security_fee', models.BooleanField(default=True)),
                ('display_college_magazine', models.BooleanField(default=True)),
                ('display_rechecking_fee', models.BooleanField(default=True)),
                ('display_reappear_fee', models.BooleanField(default=True)),
                ('display_fine', models.BooleanField(default=True)),
                ('display_institute_alumni_contribution', models.BooleanField(default=True)),
                ('display_book_bank', models.BooleanField(default=True)),
                ('batch', models.OneToOneField(db_column='batch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='batches.batches')),
            ],
            options={
                'verbose_name_plural': 'Fees',
                'db_table': 'fees',
            },
        ),
    ]
