# Generated by Django 4.2.6 on 2024-05-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilldeskOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25)),
                ('bd_order_id', models.CharField(max_length=25)),
                ('order_amount', models.CharField(max_length=12)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_response', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Billdesk Orders',
                'db_table': 'billdesk_orders',
            },
        ),
        migrations.CreateModel(
            name='BilldeskTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25)),
                ('transaction_id', models.CharField(max_length=25)),
                ('transaction_amount', models.CharField(max_length=12)),
                ('transaction_status', models.CharField(max_length=25)),
                ('payment_method', models.CharField(max_length=25)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_response', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Billdesk Transactions',
                'db_table': 'billdesk_transactions',
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=10)),
                ('tution_fee', models.CharField(default='0', max_length=8)),
                ('activity_fee', models.CharField(default='0', max_length=8)),
                ('university_fee', models.CharField(default='0', max_length=8)),
                ('security_fee', models.CharField(default='0', max_length=8)),
                ('college_magazine', models.CharField(default='0', max_length=8)),
                ('rechecking_fee', models.CharField(default='0', max_length=8)),
                ('reappear_fee', models.CharField(default='0', max_length=8)),
                ('fine', models.CharField(default='0', max_length=8)),
                ('institute_alumni_contribution', models.CharField(default='0', max_length=8)),
                ('book_bank', models.CharField(default='0', max_length=8)),
                ('total_fee', models.CharField(blank=True, max_length=8, null=True)),
                ('display_tution_fee', models.BooleanField(default=True)),
                ('display_activity_fee', models.BooleanField(default=True)),
                ('display_university_fee', models.BooleanField(default=True)),
                ('display_security_fee', models.BooleanField(default=True)),
                ('display_college_magazine', models.BooleanField(default=True)),
                ('display_rechecking_fee', models.BooleanField(default=True)),
                ('display_reappear_fee', models.BooleanField(default=True)),
                ('display_fine', models.BooleanField(default=True)),
                ('display_institute_alumni_contribution', models.BooleanField(default=True)),
                ('display_book_bank', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Fees',
                'db_table': 'fees',
            },
        ),
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('enrollment_number', models.CharField(max_length=25)),
                ('batch', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=25)),
                ('transaction_id', models.CharField(max_length=25)),
                ('transaction_amount', models.CharField(max_length=12)),
                ('transaction_status', models.CharField(max_length=25)),
                ('payment_method', models.CharField(max_length=25)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Student Fees',
                'db_table': 'student_fees',
            },
        ),
    ]
