# Generated by Django 4.2.6 on 2024-02-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilldeskOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25)),
                ('bd_order_id', models.CharField(max_length=25)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_response', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Billdesk Orders',
                'db_table': 'billdesk_orders',
            },
        ),
        migrations.CreateModel(
            name='BilldeskTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25)),
                ('transaction_id', models.CharField(max_length=25)),
                ('transaction_status', models.CharField(max_length=25)),
                ('payment_method', models.CharField(max_length=25)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_response', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Billdesk Transactions',
                'db_table': 'billdesk_transactions',
            },
        ),
    ]
