# Generated by Django 4.2.6 on 2024-02-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_billdeskorders_billdesktransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdeskorders',
            name='order_amount',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billdesktransactions',
            name='transaction_amount',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
