# Generated by Django 4.2.6 on 2024-02-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_billdeskorders_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='batch',
            field=models.CharField(default=2026, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='billdeskorders',
            table='old_billdesk_orders',
        ),
        migrations.AlterModelTable(
            name='billdesktransactions',
            table='old_billdesk_transactions',
        ),
        migrations.AlterModelTable(
            name='fees',
            table='old_fees',
        ),
    ]
