# Generated by Django 4.2.6 on 2023-11-22 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employee.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=75)),
                ('dob', models.DateField(blank=True, null=True)),
                ('full_address', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=6)),
                ('designation', models.CharField(blank=True, choices=[('Accountant', 'ACCOUNTANT'), ('Admission Counsellor', 'ADMISSION COUNSELLOR'), ('Admission Head', 'ADMISSION HEAD'), ('Assistant', 'ASSISTANT'), ('Assistant Accountant', 'ASSISTANT ACCOUNTANT'), ('Assistant Hostel Warden', 'ASSISTANT HOSTEL WARDEN'), ('Assistant Librarian', 'ASSISTANT LIBRARIAN'), ('Assistant Network Engineer', 'ASSISTANT NETWORK ENGINEER'), ('Assistant Professor', 'ASSISTANT PROFESSOR'), ('Associate Professor', 'ASSOCIATE PROFESSOR'), ('Associate Professor and HoD', 'ASSOCIATE PROFESSOR and HoD'), ('Attendant', 'ATTENDANT'), ('Chief Account Officer', 'CHIEF ACCOUNT OFFICER'), ('Clerk', 'CLERK'), ('Daftari', 'DAFTARI'), ('Dean', 'DEAN'), ('Director', 'DIRECTOR'), ('Electrical Engineer', 'ELECTRICAL ENGINEER'), ('Electrician', 'ELECTRICIAN'), ('Engineer', 'ENGINEER'), ('Executive Assistant', 'EXECUTIVE ASSISTANT'), ('Head Cook', 'HEAD COOK'), ('Helper', 'HELPER'), ('Joint Registrar', 'JOINT REGISTRAR'), ('Lab Assistant', 'LAB ASSISTANT'), ('Lab Attendant', 'LAB ATTENDANT'), ('Librarian', 'LIBRARIAN'), ('Mali', 'MALI'), ('Manager Admissions', 'MANAGER ADMISSIONS'), ('Network Engineer', 'NETWORK ENGINEER'), ('PA', 'PA'), ('Peon', 'PEON'), ('Plumber', 'PLUMBER'), ('Pro', 'PRO'), ('Professor', 'PROFESSOR'), ('Professor and HoD', 'PROFESSOR and HoD'), ('Program Manager', 'PROGRAM MANAGER'), ('Registrar', 'REGISTRAR'), ('Security Guard', 'SECURITY GUARD'), ('Senior Engineer', 'SENIOR ENGINEER'), ('Sports Instructor', 'SPORTS INSTRUCTOR'), ('Store In-Charge', 'STORE IN-CHARGE'), ('Technical Officer', 'TECHNICAL OFFICER'), ('Warden', 'WARDEN'), ('Waterman', 'WATERMAN'), ('Yoga Instructor', 'YOGA INSTRUCTOR')], max_length=27)),
                ('department', models.CharField(blank=True, choices=[('Computer Science and Engineering', 'COMPUTER SCIENCE AND ENGINEERING'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING)'), ('Computer Science and Engineering (Artificial Intelligence)', 'COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL INTELLIGENCE)'), ('Computer Science and Engineering (Data Science)', 'COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE)'), ('Information Technology', 'INFORMATION TECHNOLOGY'), ('Electronics and Communication Engineering', 'ELECTRONICS AND COMMUNICATION ENGINEERING'), ('Mechanical and Automation Engineering', 'MECHANICAL AND AUTOMATION ENGINEERING'), ('Applied Science', 'APPLIED SCIENCE'), ('Mechanical Engineering', 'MECHANICAL ENGINEERING'), ('Electrical and Electronics Engineering', 'ELECTRICAL AND ELECTRONICS ENGINEERING'), ('Artificial Intelligence and Machine Learning', 'ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING'), ('Artificial Intelligence and Data Science', 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE'), ('Information Technology and Engineering', 'INFORMATION TECHNOLOGY AND ENGINEERING'), ('Computer Science and Technology', 'COMPUTER SCIENCE AND TECHNOLOGY'), ('Bachelor of Business Administration', 'BACHELOR OF BUSINESS ADMINISTRATION'), ('Master of Business Administration', 'MASTER OF BUSINESS ADMINISTRATION'), ('Administration', 'ADMINISTRATION')], max_length=79)),
                ('bloodgroup', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('emergency_name', models.CharField(blank=True, max_length=75)),
                ('emergency_number', models.CharField(blank=True, max_length=10)),
                ('passport_photograph', models.ImageField(blank=True, null=True, upload_to=employee.utils.passport_photograph_rename)),
                ('aadhar', models.FileField(blank=True, null=True, upload_to=employee.utils.aadhar_rename)),
                ('pancard', models.FileField(blank=True, null=True, upload_to=employee.utils.pancard_rename)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Personal Details',
                'db_table': 'employee_personal_details',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
            },
        ),
    ]
