# Generated by Django 4.2.6 on 2023-10-18 18:29

from django.db import migrations, models
import student.utils


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(db_index=True, max_length=11, unique=True)),
                ('ipu_registration_number', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(blank=True, max_length=75)),
                ('dob', models.DateField()),
                ('full_address', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(blank=True, max_length=6)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(blank=True, max_length=15)),
                ('father_name', models.CharField(blank=True, max_length=75)),
                ('mother_name', models.CharField(blank=True, max_length=75)),
                ('father_qualification', models.CharField(blank=True, max_length=30)),
                ('mother_qualification', models.CharField(blank=True, max_length=30)),
                ('father_occupation', models.CharField(blank=True, max_length=30)),
                ('mother_occupation', models.CharField(blank=True, max_length=30)),
                ('father_job_designation', models.CharField(blank=True, max_length=50)),
                ('mother_job_designation', models.CharField(blank=True, max_length=50)),
                ('father_business_type', models.CharField(blank=True, max_length=50)),
                ('mother_business_type', models.CharField(blank=True, max_length=50)),
                ('father_mobile_number', models.CharField(blank=True, max_length=10)),
                ('mother_mobile_number', models.CharField(blank=True, max_length=10)),
                ('father_office_address', models.CharField(blank=True, max_length=100)),
                ('mother_office_address', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=75)),
                ('board_12th', models.CharField(blank=True, max_length=100)),
                ('year_of_12th', models.PositiveIntegerField(blank=True, null=True)),
                ('rollno_12th', models.PositiveBigIntegerField(blank=True, null=True)),
                ('school_12th', models.CharField(blank=True, max_length=150)),
                ('aggregate_12th', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('board_10th', models.CharField(blank=True, max_length=100)),
                ('year_of_10th', models.PositiveIntegerField(blank=True, null=True)),
                ('rollno_10th', models.PositiveBigIntegerField(blank=True, null=True)),
                ('school_10th', models.CharField(blank=True, max_length=150)),
                ('aggregate_10th', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jee_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('jee_percentile', models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True)),
                ('jee_rollno', models.CharField(blank=True, max_length=12)),
                ('special_achievements', models.CharField(blank=True, max_length=200)),
                ('passport_photograph', models.ImageField(blank=True, upload_to=student.utils.passport_photograph_rename)),
                ('marksheet_10th', models.FileField(blank=True, upload_to=student.utils.marksheet_10th_rename)),
                ('marksheet_12th', models.FileField(blank=True, upload_to=student.utils.marksheet_12th_rename)),
                ('aadhar', models.FileField(blank=True, upload_to=student.utils.aadhar_rename)),
                ('pancard', models.FileField(blank=True, upload_to=student.utils.pancard_rename)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Student Personal Details',
                'db_table': 'student_personal_details',
            },
        ),
    ]
