# Generated by Django 4.2.6 on 2023-10-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
