# Generated by Django 4.2.6 on 2023-10-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentdetails_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='category',
            field=models.CharField(blank=True, choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('UR/Gen', 'UR/Gen'), ('EWS', 'EWS'), ('PH', 'PH (Physically Handicapped/Person with Disability)'), ('DEFENCE', 'Defence'), ('J_AND_K_MIGRANT', 'J & K Migrant')], max_length=15),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='region',
            field=models.CharField(blank=True, choices=[('DELHI', 'Delhi'), ('OUTSIDE_DELHI', 'Outside Delhi')], max_length=13),
        ),
    ]
