# Generated by Django 4.2.6 on 2024-02-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_studentgroups_counsellorgroups'),
        ('branches', '0001_initial'),
        ('student', '0008_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(db_column='branch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branches'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(db_column='group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groups'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_lateral_entry',
            field=models.BooleanField(default=False),
        ),
    ]
