# Generated by Django 4.2.6 on 2023-11-26 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0009_alter_studentgroups_group_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroups',
            options={'verbose_name_plural': 'Student-Groups'},
        ),
        migrations.RemoveField(
            model_name='studentgroups',
            name='student',
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='student_id',
            field=models.OneToOneField(db_column='student_id', default='01296402722', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='student_name',
            field=models.CharField(default='ggc', max_length=75),
            preserve_default=False,
        ),
    ]
