# Generated by Django 4.2.6 on 2024-03-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('groups', '0002_studentgroups_counsellorgroups'),
        ('batches', '0001_initial'),
        ('student', '0009_student_branch_student_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, db_column='batch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='batches.batches'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branches'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groups'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_lateral_entry',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
