# Generated by Django 4.2.6 on 2024-03-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('package_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role_offered', models.CharField(max_length=100)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='active_placement_pdfs/')),
                ('placement_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PastPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('package_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role_offered', models.CharField(max_length=100)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='past_placement_pdfs/')),
                ('placement_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('package_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role_offered', models.CharField(max_length=100)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='placement_pdfs/')),
                ('placement_date', models.DateField()),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacementAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='placement_announcement_documents/')),
            ],
        ),
    ]
