# Generated by Django 4.2.6 on 2024-04-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_activeplacements_announcement_pastplacements_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlacementOfficer',
        ),
        migrations.AddField(
            model_name='activeplacements',
            name='docs',
            field=models.FileField(null=True, upload_to='assets/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='docs',
            field=models.FileField(null=True, upload_to='assets/'),
        ),
        migrations.AddField(
            model_name='pastplacements',
            name='docs',
            field=models.FileField(null=True, upload_to='assets/'),
        ),
        migrations.AddField(
            model_name='placements',
            name='docs',
            field=models.FileField(null=True, upload_to='assets/'),
        ),
    ]
