# Generated by Django 4.2.6 on 2024-04-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_delete_activeplacements_delete_pastplacements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='hidden',
        ),
    ]
