# Generated by Django 4.2.6 on 2024-04-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_remove_announcement_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
