# Generated by Django 4.2.6 on 2024-04-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_rename_archived_announcement_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='placements',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
