# Generated by Django 4.2.6 on 2024-05-06 22:24

from django.db import migrations, models
import placement.models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0008_placements_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=placement.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='placements',
            name='date',
            field=models.DateField(default=placement.models.get_current_date),
        ),
    ]
